### ISSUE TITLE
recorder.result.upload form error

### ISSUE THREAD

**Issue by bobzsj87** [normanzb/playcorder-core-as3#11]
The upload form data is not a standard post form, but an array of raw data. Upload needs to be a standard multipart form data so that server can handle it correctly. Chrome inspection of this form shown here

![screen shot 2013-11-06 at 11 16 43 pm](https://f.cloud.github.com/assets/568939/1483381/84b88ce6-46f6-11e3-8d66-dc6ba37a4321.png)

**Comment by normanzb** [comment]
ver 0.2.1 should partially fixed the issue, now it is posting raw data rather than byte sequence string.

however, it is still using a standard post because it is sufficient for data uploading in most case and can be easily handled by backend.

multipart is still a TODO and duplicated with issue #3

**Comment by bobzsj87** [comment]
the upload request to the server is marked as Content-Type:application/x-www-form-urlencoded. Server side cannot decode the formdata based on this, should be like multipart/form-data or plain text, or something else
